#! /bin/sh

#
#
#    ▄▄▄▄     ██████  ██▓███   █     █░ ███▄ ▄███▓
#    ▓█████▄ ▒██    ▒ ▓██░  ██▒▓█░ █ ░█░▓██▒▀█▀ ██▒
#    ▒██▒ ▄██░ ▓██▄   ▓██░ ██▓▒▒█░ █ ░█ ▓██    ▓██░
#    ▒██░█▀    ▒   ██▒▒██▄█▓▒ ▒░█░ █ ░█ ▒██    ▒██ 
#    ░▓█  ▀█▓▒██████▒▒▒██▒ ░  ░░░██▒██▓ ▒██▒   ░██▒
#    ░▒▓███▀▒▒ ▒▓▒ ▒ ░▒▓▒░ ░  ░░ ▓░▒ ▒  ░ ▒░   ░  ░
#    ▒░▒   ░ ░ ░▒  ░ ░░▒ ░       ▒ ░ ░  ░  ░      ░
#     ░    ░ ░  ░  ░  ░░         ░   ░  ░      ░   
#     ░            ░               ░           ░   
#          ░                                       
#

# #######################################################################
# #                             FUNCTIONS                               #
# #######################################################################

# Credits to 6gk/polka
rule() { bspc rule -a "$@" & }
config() { bspc config "$@" & }
start() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

# #######################################################################
# #                            AUTOSTART                                #
# #######################################################################

# Keybindigs
pgrep -x sxhkd > /dev/null || sxhkd &

# Fix Cursor
xsetroot -cursor_name left_ptr &

# Disable buttons on gtk apps
gsettings set org.gnome.desktop.wm.preferences button-layout ""

# Compositor
picom &

# Polybar
$HOME/.config/polybar/launch.sh &

# Notify Daemon
dunst &

# Polkit
[ -n "$(pidof polkit-gnome-authentication-agent-1)" ] || /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Spotify
[ -n "$(pidof spotify)" ] || spotify &

# Kotatogram 
[ -n "$(pidof kotatogram-desktop)" ] || kotatogram-desktop &

# Wallpaper
$HOME/.fehbg &

# #######################################################################
# #                               RULES                                 #
# ####################################################################### 

rule Brave-browser         desktop='^2'
rule KotatogramDesktop     desktop='^3'
rule discord               desktop='^6'
rule Transmission-gtk      desktop='^5'
rule Gimp-2.10             desktop='^6'
rule mpv                   desktop='^6' state=fullscreen
rule Leafpad               state=floating 
rule Viewnior              state=floating
rule Thunar                state=floating 
rule Galculator            state=floating
rule Gucharmap             state=floating
rule Gpick                 state=floating
rule Gcolor2               state=floating
rule Engrampa              state=floating
rule Lxappearance          state=floating 

config external_rules_command "$HOME/.config/bspwm/scripts/spotifyrule.sh"

# #######################################################################
# #                           GENERAL CONFIG                            #
# #######################################################################

bspc monitor -d 1 2 3 4 5 6 

config border_width             3
config window_gap               10
config split_ratio              0.50

config borderless_monocle       true
config gapless_monocle          true
bspc config paddingless_monocle true
bspc config single_monocle      false
#config focus_follows_pointer   true
config top_padding              40
config bottom_padding           100
config left_padding             50
config right_padding            50

config pointer_modifier         mod4
config pointer_action1          move
config pointer_action2          resize_side
config pointer_action2          resize_corner

config focused_border_color     "#0f0f0f"
config normal_border_color      "#0f0f0f"
config active_border_color      "#4c4c4c"

start borders
